name: Check Target Branch

on:
  pull_request:
    branches:
      - '**'

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target
        run: |
          if [[ "${{ github.actor }}" == "ZL-Asica" || "${{ github.actor }}" == "dependabot" ]]; then
            exit 0
          fi

          if [[ "${{ github.event.pull_request.base.ref }}" == "main" || "${{ github.event.pull_request.base.ref }}" == "blog" ]]; then
            echo "::error::This PR targets the wrong branch (${ {github.event.pull_request.base.ref} }). Please change the target branch to 'dev'."
            exit 1
          else
            echo "Target branch is valid (${ {github.event.pull_request.base.ref} })."
          fi
